<?php

namespace AppBundle\Repository;

/**
 * item_listRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class item_listRepository extends \Doctrine\ORM\EntityRepository
{
}
